### ISSUE TITLE
Docker build throws an outdated pip error message

### ISSUE THREAD

**Issue by charaka1** [mobernabeu/docker-polnet#1]
When I execute, "docker build -t polnet .", the following error message can be seen:

Step 4/15 : RUN pip install matplotlib
 ---> Running in 1fc189e84b51
Downloading/unpacking matplotlib
  Running setup.py (path:/tmp/pip_build_root/matplotlib/setup.py) egg_info for package matplotlib
    
    Matplotlib 3.0+ does not support Python 2.x, 3.0, 3.1, 3.2, 3.3, or 3.4.
    Beginning with Matplotlib 3.0, Python 3.5 and above is required.
    
    This may be due to an out of date pip.
    
    Make sure you have pip >= 9.0.1.
    
    Complete output from command python setup.py egg_info:
    

Matplotlib 3.0+ does not support Python 2.x, 3.0, 3.1, 3.2, 3.3, or 3.4.

Beginning with Matplotlib 3.0, Python 3.5 and above is required.

This may be due to an out of date pip.

Make sure you have pip >= 9.0.1.

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/matplotlib
Storing debug log for failure in /home/ubuntu/.pip/pip.log
The command '/bin/sh -c pip install matplotlib' returned a non-zero code: 1

**Comment by mobernabeu** [comment]
Pip now updates itself before going ahead (0b59ff0).
